dynamic_title: false
live_config_reload: true
render_timer: false

env:
  TERM: xterm-256color-italic

shell:
  program: /usr/local/bin/zsh
  args:
    - --login

window:
  dimensions:
    columns: 240
    lines: 81
  padding:
    x: 1
    y: 1
  decorations: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrollback_lines: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

visual_bell:
  animation: Linear
  duration: 0

tabspaces: 8
draw_bold_text_with_bright_colors: true

font:
  normal:
    family: Operator Mono
    style: Book
  bold:
    family: Operator Mono
    style: Book
  italic:
    family: Operator Mono
    style: Light Italic
  size: 15.0
  offset:
    x: 0.0
    y: 0.0
  glyph_offset:
    x: 0.0
    y: 0.0
  use_thin_strokes: true

cursor_style: Block
custom_cursor_colors: true
hide_cursor_when_typing: false
unfocused_hollow_cursor: true

background_opacity: 1.0
colors:
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  cursor:
    cursor: '0xabb2bf'
    text:   '0x282c34'

  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  bright:
    black:   '0x545862'
    red:     '0xd19a66' # yellow
    green:   '0x353b45' # dark grey
    yellow:  '0x3e4451' # medium grey
    blue:    '0x565c64' # normal grey
    magenta: '0xb6bdca' # light grey
    cyan:    '0xbe5046' # red
    white:   '0xc8ccd4'

#   dim:
#     black:   '0x333333'
#     red:     '0xf2777a'
#     green:   '0x99cc99'
#     yellow:  '0xffcc66'
#     blue:    '0x6699cc'
#     magenta: '0xcc99cc'
#     cyan:    '0x66cccc'
#     white:   '0xdddddd'

# use `xxd -psd` to generate key-codes
# This is using screen-style ^A but maybe tmux-style ^B is better
key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: D, mods: Command|Shift, chars: "\x01\x2d" }
  - { key: D, mods: Command, chars: "\x01\x7c" }
  - { key: W, mods: Command, chars: "\x01\x78" }
  - { key: T, mods: Command, chars: "\x01\x63" }

# There's a buttload of default keybinds. I'll add them back
# as I work through what I actually need.
