---
Layout/LineLength:
  Max: 120

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/TrailingEmptyLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
