export BROWSER='open'
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export DEFAULT_USER='colin'
export HOMEBREW_NO_ANALYTICS=1
export LANG='en_CA.UTF-8'

export GOPATH=$HOME
export FZF_DEFAULT_OPTS='--bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all --color fg:4,hl:8,fg+:15,bg+:0,hl:4,info:8,prompt:3,pointer:4,spinner:4,marker:4'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH=$HOME/src/bin:$PATH
export SHOPIFY=$HOME/src/github.com/Shopify/shopify
export BOURGEOIS=$HOME/src/github.com/Shopify/bourgeois
#export XDG_CONFIG_HOME=$HOME/.config

export LESS_TERMCAP_mb=$(printf '\e[03;37m') # Start Blinking Mode
export LESS_TERMCAP_md=$(printf '\e[00;35m') # Start double-bright
export LESS_TERMCAP_me=$(printf '\e[0m')     # Turn off everything
export LESS_TERMCAP_so=$(printf '\e[00;36m') # Standout Start
export LESS_TERMCAP_se=$(printf '\e[0m')     # Standout End
export LESS_TERMCAP_us=$(printf '\e[03;34m') # Underline Start
export LESS_TERMCAP_ue=$(printf '\e[0m')     # Underline End
export LESS='-F -g -i -M -R -S -w -X -z-4'
typeset -gU cdpath fpath mailpath path

cdpath=(
  $cdpath
  $HOME/src/github.com/shopify
  $HOME/src/github.com/colinstein
)

path=(
  /usr/local/{bin,sbin}
  $HOME/.cargo/bin
  $path
)

