export BROWSER='open'

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export DEFAULT_USER='colin'
export HOMEBREW_NO_ANALYTICS=1
export TERM=xterm-256color-italic
export LANG='en_CA.UTF-8'

export GOPATH=$HOME/Code/go
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH=$HOME/Code/go/bin:$PATH

export LESS_TERMCAP_mb=$(printf '\e[03;37m') # Start Blinking Mode
export LESS_TERMCAP_md=$(printf '\e[00;35m') # Start double-bright
export LESS_TERMCAP_me=$(printf '\e[0m')     # Turn off everything
export LESS_TERMCAP_so=$(printf '\e[00;36m') # Standout Start
export LESS_TERMCAP_se=$(printf '\e[0m')     # Standout End
export LESS_TERMCAP_us=$(printf '\e[03;34m') # Underline Start
export LESS_TERMCAP_ue=$(printf '\e[0m')     # Underline End
export LESS='-F -g -i -M -R -S -w -X -z-4'

typeset -gU cdpath fpath mailpath path

cdpath=(
  $cdpath
)

path=(
  /usr/local/{bin,sbin}
  $path
)
